export const streams = {
  meta: { cache: "2021-02-23T12:01:49.223Z" },
  data: [
    {
      members: [{ name: "天音かなた" }],
      id: "9A8RKOJMwSg",
      url: "https://www.youtube.com/watch?v=9A8RKOJMwSg",
      thumbnail: "https://img.youtube.com/vi/9A8RKOJMwSg/mqdefault.jpg",
      startTime: 1613919960000,
      isStreaming: false,
      producer: "Hololive",
    },
    {
      members: [{ name: "天音かなた" }],
      id: "5-T4hj9vR0Y",
      url: "https://www.youtube.com/watch?v=5-T4hj9vR0Y",
      thumbnail: "https://img.youtube.com/vi/5-T4hj9vR0Y/mqdefault.jpg",
      startTime: 1613923200000,
      isStreaming: false,
      producer: "Hololive",
    },
    {
      members: [{ name: "角巻わため" }],
      id: "MH7CjoYlLCI",
      url: "https://www.youtube.com/watch?v=MH7CjoYlLCI",
      thumbnail: "https://img.youtube.com/vi/MH7CjoYlLCI/mqdefault.jpg",
      startTime: 1613943120000,
      isStreaming: false,
      producer: "Hololive",
    },
    {
      members: [{ name: "雪花ラミィ" }],
      id: "w8znycDFPtU",
      url: "https://www.youtube.com/watch?v=w8znycDFPtU",
      thumbnail: "https://img.youtube.com/vi/w8znycDFPtU/mqdefault.jpg",
      startTime: 1613952060000,
      isStreaming: false,
      producer: "Hololive",
    },
    {
      members: [{ name: "潤羽るしあ" }],
      id: "UqusB-u4O_U",
      url: "https://www.youtube.com/watch?v=UqusB-u4O_U",
      thumbnail: "https://img.youtube.com/vi/UqusB-u4O_U/mqdefault.jpg",
      startTime: 1613980800000,
      isStreaming: false,
      producer: "Hololive",
    },
    {
      members: [{ name: "猫又おかゆ" }],
      id: "RxytWppYJq8",
      url: "https://www.youtube.com/watch?v=RxytWppYJq8",
      thumbnail: "https://img.youtube.com/vi/RxytWppYJq8/mqdefault.jpg",
      startTime: 1613996460000,
      isStreaming: false,
      producer: "Hololive",
    },
    {
      members: [{ name: "猫又おかゆ" }],
      id: "j6P_m6adkgc",
      url: "https://www.youtube.com/watch?v=j6P_m6adkgc",
      thumbnail: "https://img.youtube.com/vi/j6P_m6adkgc/mqdefault.jpg",
      startTime: 1614000600000,
      isStreaming: false,
      producer: "Hololive",
    },
    {
      members: [{ name: "天音かなた" }],
      id: "1HWLCBUUsQI",
      url: "https://www.youtube.com/watch?v=1HWLCBUUsQI",
      thumbnail: "https://img.youtube.com/vi/1HWLCBUUsQI/mqdefault.jpg",
      startTime: 1614000960000,
      isStreaming: false,
      producer: "Hololive",
    },
    {
      members: [{ name: "尾丸ポルカ" }],
      id: "UpoysjZfWrU",
      url: "https://www.youtube.com/watch?v=UpoysjZfWrU",
      thumbnail: "https://img.youtube.com/vi/UpoysjZfWrU/mqdefault.jpg",
      startTime: 1614002400000,
      isStreaming: false,
      producer: "Hololive",
    },
    {
      members: [{ name: "角巻わため" }],
      id: "px-uTzmyjDY",
      url: "https://www.youtube.com/watch?v=px-uTzmyjDY",
      thumbnail: "https://img.youtube.com/vi/px-uTzmyjDY/mqdefault.jpg",
      startTime: 1614002460000,
      isStreaming: false,
      producer: "Hololive",
    },
    {
      members: [{ name: "雪花ラミィ" }],
      id: "x5UKFwBQC-Y",
      url: "https://www.youtube.com/watch?v=x5UKFwBQC-Y",
      thumbnail: "https://img.youtube.com/vi/x5UKFwBQC-Y/mqdefault.jpg",
      startTime: 1614002520000,
      isStreaming: false,
      producer: "Hololive",
    },
    {
      members: [{ name: "常闇トワ" }],
      id: "M_KM_6tfBIE",
      url: "https://www.youtube.com/watch?v=M_KM_6tfBIE",
      thumbnail: "https://img.youtube.com/vi/M_KM_6tfBIE/mqdefault.jpg",
      startTime: 1614002520000,
      isStreaming: false,
      producer: "Hololive",
    },
    {
      members: [{ name: "常闇トワ" }],
      id: "W6sYUip4gT0",
      url: "https://www.youtube.com/watch?v=W6sYUip4gT0",
      thumbnail: "https://img.youtube.com/vi/W6sYUip4gT0/mqdefault.jpg",
      startTime: 1614003780000,
      isStreaming: false,
      producer: "Hololive",
    },
    {
      members: [{ name: "宝鐘マリン" }],
      id: "W6GgSLr_6qk",
      url: "https://www.youtube.com/watch?v=W6GgSLr_6qk",
      thumbnail: "https://img.youtube.com/vi/W6GgSLr_6qk/mqdefault.jpg",
      startTime: 1614004200000,
      isStreaming: false,
      producer: "Hololive",
    },
    {
      members: [{ name: "天音かなた" }],
      id: "s9EZiXwy4Hc",
      url: "https://www.youtube.com/watch?v=s9EZiXwy4Hc",
      thumbnail: "https://img.youtube.com/vi/s9EZiXwy4Hc/mqdefault.jpg",
      startTime: 1614018000000,
      isStreaming: false,
      producer: "Hololive",
    },
    {
      members: [{ name: "獅白ぼたん" }],
      id: "10V-1piTUdw",
      url: "https://www.youtube.com/watch?v=10V-1piTUdw",
      thumbnail: "https://img.youtube.com/vi/10V-1piTUdw/mqdefault.jpg",
      startTime: 1614049200000,
      isStreaming: false,
      producer: "Hololive",
    },
    {
      members: [{ name: "宝鐘マリン" }],
      id: "g9pegmhQo7M",
      url: "https://www.youtube.com/watch?v=g9pegmhQo7M",
      thumbnail: "https://img.youtube.com/vi/g9pegmhQo7M/mqdefault.jpg",
      startTime: 1614056400000,
      isStreaming: true,
      producer: "Hololive",
    },
    {
      title:
        "【雀魂】初心から雀士にあがれたら嬉しいやん【にじさんじ/山神カルタ】",
      description:
        "あと少しがたりない\n\n素敵なイラスト : 東雲(@ dawn13_33)さま\n\n✰⋆｡:ﾟ･*☽:ﾟ･⋆｡✰⋆｡:ﾟ･*☽:ﾟ･⋆｡✰⋆｡:ﾟ･*☽⋆｡:ﾟ･*✰⋆｡:ﾟ･*☽⋆｡\n\n現在販売中のボイス🎙⋆｡\n\nバレンタインデーボイス💝🍫\nhttps://shop.nijisanji.jp/s/niji/item/detail/dig-00300?ima=3514\n\n2月マンスリーボイス🍛\nhttps://shop.nijisanji.jp/s/niji/item/detail/dig-00284\n\n✰⋆｡:ﾟ･*☽:ﾟ･⋆｡✰⋆｡:ﾟ･*☽:ﾟ･⋆｡✰⋆｡:ﾟ･*☽⋆｡:ﾟ･*✰⋆｡:ﾟ･*☽⋆｡\n\nにじさんじ所属バーチャルライバー　\n見習い烏天狗の山神カルタです。\n普段は山で修行をしています。\nいろんな時間をみんなと一緒に過ごせたら嬉しいなあ。\n\n\n✰⋆｡:ﾟ･*☽:ﾟ･⋆｡✰⋆｡:ﾟ･*☽:ﾟ･⋆｡✰⋆｡:ﾟ･*☽⋆｡:ﾟ･*✰⋆｡:ﾟ･*☽⋆｡\n\n\n🎴Twitter tag🎴\n\n配信タグ : #山神カタル\nイラスト : # カルタの絵札\n\n〔 Twitter 〕\n https://twitter.com/Karuta_Yamagami\n\nおてがみやお問い合わせなど！💌📞\nhttps://nijisanji.ichikara.co.jp/cont...\n\n🎴メンバーシップはこちらから(月額490円)🎴\nhttps://www.youtube.com/channel/UCllKI7VjyANuS1RXatizfLQ/join\n→\n名前の横にバッジ！\nコメント欄で使えるスタンプ！\n\nメンバー限定配信や、ほぼ毎日コミュニティー投稿もあり！\n山神の食生活がのぞけます🍚\n\n\n✰⋆｡:ﾟ･*☽:ﾟ･⋆｡✰⋆｡:ﾟ･*☽:ﾟ･⋆｡✰⋆｡:ﾟ･*☽⋆｡:ﾟ･*✰⋆｡:ﾟ･*☽⋆｡\n\n#山神カルタ",
      members: [
        {
          id: 98,
          name: "山神カルタ",
          avatar:
            "https://liver-icons.s3-ap-northeast-1.amazonaws.com/400x400/Karuta_Yamagami_20200202.png",
          color: "#384b5a",
        },
      ],
      id: "vEPlKC57x58",
      url: "https://www.youtube.com/watch?v=vEPlKC57x58",
      thumbnail: "https://img.youtube.com/vi/vEPlKC57x58/mqdefault.jpg",
      startTime: 1614061800000,
      endTime: 1614065400000,
      isStreaming: false,
      producer: "にじさんじ",
    },
    {
      members: [{ name: "兎田ぺこら" }],
      id: "Jzw6ZZUJQ7E",
      url: "https://www.youtube.com/watch?v=Jzw6ZZUJQ7E",
      thumbnail: "https://img.youtube.com/vi/Jzw6ZZUJQ7E/mqdefault.jpg",
      startTime: 1614081600000,
      isStreaming: false,
      producer: "Hololive",
    },
    {
      title: "【雑談】ましまろを「丁寧に」たべる【戌亥とこ/にじさんじ】",
      description:
        "いつも丁寧ですけどね！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！\n\n\n【配信タグ】\n#いぬいどんどんすきになる\n\n◆その他諸々◆\n▼メンバーシップの登録はコチラ\nhttps://www.youtube.com/channel/UCXRlIK3Cw_TJIQC5kSJJQMg/join\n\n【Twitter】\nhttps://twitter.com/inui_toko\n\n【公式オンラインショップ】\nhttps://nijisanji.booth.pm/\n\n【ファンレターの送付先はリンクから確認してな～】\nhttps://nijisanji.ichikara.co.jp/contact/\n\n【Pixiv fanbox】\nhttps://www.pixiv.net/fanbox/creator/24113985\n\n【にじさんじ公式Twitter】\nhttps://twitter.com/nijisanji_app\n《@nijisanji_app 》\n\n【にじさんじ公式HP】\nhttps://nijisanji.ichikara.co.jp/\n\n【BGM使わせていただいてるサイト】\nhttps://dova-s.jp/",
      members: [
        {
          id: 71,
          name: "戌亥とこ",
          avatar:
            "https://s3-ap-northeast-1.amazonaws.com/liver-icons/400x400/Inui_Toko.png",
          color: "#9d3757",
        },
      ],
      id: "fftZgt4wrtI",
      url: "https://www.youtube.com/watch?v=fftZgt4wrtI",
      thumbnail: "https://img.youtube.com/vi/fftZgt4wrtI/mqdefault.jpg",
      startTime: 1614081600000,
      endTime: 1614085200000,
      isStreaming: false,
      producer: "にじさんじ",
    },
    {
      members: [{ name: "桐生ココ" }],
      id: "Ezs9kJI8f90",
      url: "https://www.youtube.com/watch?v=Ezs9kJI8f90",
      thumbnail: "https://img.youtube.com/vi/Ezs9kJI8f90/mqdefault.jpg",
      startTime: 1614085200000,
      isStreaming: false,
      producer: "Hololive",
    },
    {
      members: [{ name: "雪花ラミィ" }],
      id: "WrCvzVwCX2k",
      url: "https://www.youtube.com/watch?v=WrCvzVwCX2k",
      thumbnail: "https://img.youtube.com/vi/WrCvzVwCX2k/mqdefault.jpg",
      startTime: 1614088800000,
      isStreaming: false,
      producer: "Hololive",
    },
  ],
};
